# GitHub Actions workflow for automated deployment
name: Deploy to Digital Ocean

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/rituo
          git pull origin main
          docker-compose -f docker-compose.production.yml --env-file .env.production down
          docker-compose -f docker-compose.production.yml --env-file .env.production build --no-cache
          docker-compose -f docker-compose.production.yml --env-file .env.production up -d
          
          # Health check
          sleep 30
          if curl -f http://localhost:8000/health; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed - health check failed"
            exit 1
          fi

    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "🚀 Deployment completed successfully!"
        else
          echo "❌ Deployment failed!"
        fi
